### ISSUE TITLE
Lien des réseaux sociaux sur preprod/ico

### ISSUE THREAD

**Issue by Yannick-enzym** [enzymApp/ico-website#18]
Les liens des comptes telegram et Facebook sont a modifier en fonction de la langue choisie, pour les autres, on est bon.

le TELEGRAM bleu en bas à droite **et** celui parmi les autres réseaux sociaux:

EN
https://t.me//enzym_app

FR
https://t.me//enzym_fr

FACEBOOK

EN
https://www.facebook.com/Enzymapp/

FR
https://www.facebook.com/Enzym.Francais/

**Comment by slaivyn** [comment]
@AlexGraphicDesign tu sais comme faire ça ou je m'en occupe ?
Tu peux le faire dans la dernière pull request
