### ISSUE TITLE
Bandeau à droite

### ISSUE THREAD

**Issue by slaivyn** [enzymApp/ico-website#2]
- 2 parties :
  - la phase en cours et ses conditions :
    - en ce moment c'est la Private Sale
    - dates
    - prix du ZYM
  - en dessous, la prochaine phase (Sale) et ses conditions
- bouton "contact us"

**Comment by Yannick-enzym** [comment]
on a fait un petit croquis vite fait
![schema site ico- encart token sales](https://user-images.githubusercontent.com/43010275/49507513-e2d65600-f880-11e8-972b-fdce5c5e9cb3.jpg)

**Comment by slaivyn** [comment]
c'est le cadre à gauche seulement sur le croquis.
La phase "en cours" est encadré (ou mise en évidence d'une manière ou d'une autre), l'autre phase peut-être grisée ou plus petit ou autre. Ce qu'il faut c'est que l'on comprenne bien l'idée qu'en ce moment c'est très intéressant d'acheter :D
Pour les dates on hésite encore entre 2 possibilités : mettre des dates précises ou mettre quelque chose de plus flou (ex : "soon" ou "early 2019") vu que ça risque de bouger

**Comment by slaivyn** [comment]
Rendu sur un mac 13" :

https://media.discordapp.net/attachments/436180821653716992/522823057853775873/Capture_decran_2018-12-13_a_18.11.59.png?width=884&height=500

Je pense que le cadre droit est trop gros.
Et le problème d'adaptation de la hauteur est là aussi bien visible

**Comment by slaivyn** [comment]
Rendu sur un mac 13" :

https://media.discordapp.net/attachments/436180821653716992/522823057853775873/Capture_decran_2018-12-13_a_18.11.59.png?width=884&height=500

Je pense que le cadre droit est trop gros.
Et le problème d'adaptation de la hauteur est là aussi bien visible

**Comment by AlexGraphicDesign** [comment]
Modification effectuée sur la branche 'alexrequest'
