### ISSUE TITLE
"about Enzym" Ajouter le texte

### ISSUE THREAD

**Issue by Yannick-enzym** [enzymApp/ico-website#4]
Enzym is a new real life mobile game which sends players out to meet new people in the real world. Players respond to quests on their smartphones with or without augmented reality which actually gets players to socialize with new people.

Enzym ‘s playground is the players local area and they move around within their neighborhood , this allows the app to respond to the players main habit on their mobiles : immediacy. The quests usually start or end in a private establishment or space open to public which allows the players to meet new people in a safe environment.

Enzym encourages players to create a social network who regularly play together. The players reputation has a key role to ensure, in a non-partisan way, which controls the interactions between players. It is built by adding up objective consequences (for example the number of messages unanswered) and also subjective ones (such as satisfaction of another player after meeting them). This mechanism encourages positive behavior as well as giving enough information to the players to allow them to determine whether they are interested in an encounter or not.

Enzym is a transparent Ethereum Blockchain based app. The ZYM with its token ERC-20 is the fuel for the app: Most actions either require ZYMs or allows the player to win them.

Establishments will be able to buy ZYMs and organize distributions within their premises to encourage the Enzym community to come and discover them. They will be able to consult precise statistics on the attendance following these distributions, based on information taken directly from Blockchain. Enzym will provide other tools to improve knowledge about the target clientele and its retention while always respecting the player’s confidentiality. The ZYM and their mode of distribution allows the player to have access to a free app, with no publicity or premium accounts as well as maintaining a solid and reliant business model.

Ajouter un commentaire…

**Comment by AlexGraphicDesign** [comment]
Je viens d'ajouter le texte dans l'appli (anglaise et traduction Française à vérifier du coup)

**Comment by slaivyn** [comment]
@Yannick-enzym tu as fourni à @AlexGraphicDesign la version FR ?

**Comment by AlexGraphicDesign** [comment]
Yannick me l'a bien fournie oui, elle est intégrée
