### ISSUE TITLE
Afficher l'adresse mail de contact

### ISSUE THREAD

**Issue by slaivyn** [enzymApp/ico-website#6]
Dans l'encart à droite, en bas, un texte du type : "Contact-us: ico@enzym.io"
Il faut que ça soit bien visible

**Comment by AlexGraphicDesign** [comment]
Done dans mon pull request de ce jour

**Comment by slaivyn** [comment]
Il faudrait afficher seulement l'adresse mail, mais sous forme d'une image.
Si tu as besoin d'aide pour créer l'image, je peux demander à un pote qui fera ça en 2 minutes

**Comment by AlexGraphicDesign** [comment]
Modification effectuée, sur ma branche 'alexrequest' je vais utiliser une autre branche pour les modifications suivantes comme tu m'as dit
